# Generated by Django 5.1.3 on 2024-11-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('descrition', models.TextField(max_length=150, verbose_name='описание')),
                ('sum_debts', models.IntegerField(verbose_name='сумма долгов')),
                ('expiration_date', models.DateTimeField(verbose_name='дата истечения')),
                ('creation_date', models.DateTimeField(verbose_name='дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='долг')),
            ],
        ),
    ]
