# Generated by Django 5.1.3 on 2024-11-09 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель'),
        ),
        migrations.AddField(
            model_name='bill',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.group', verbose_name='группа'),
        ),
        migrations.AddField(
            model_name='debt',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='bills.bill', verbose_name='счет'),
        ),
        migrations.AddField(
            model_name='debt',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.currency'),
        ),
        migrations.AddField(
            model_name='debt',
            name='user_from',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='долг от кого'),
        ),
        migrations.AddField(
            model_name='debt',
            name='user_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='debt_to', to=settings.AUTH_USER_MODEL, verbose_name='долг кому'),
        ),
    ]
