# Generated by Django 5.1.3 on 2024-11-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='paided',
            field=models.IntegerField(default=0, verbose_name='заплачено'),
            preserve_default=False,
        ),
    ]
