# Generated by Django 4.2.16 on 2024-11-10 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_group_creator_alter_group_logo_alter_user_avatar'),
        ('bills', '0003_debt_paided'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='descrition',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='bill',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='user.group', verbose_name='группа'),
        ),
    ]
