# Generated by Django 4.2.16 on 2024-11-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_rename_descrition_bill_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
